site_name: Longchamps Protocols
theme:
  logo: assets/FDL_Logo.png
  favicon: assets/favicon/favicon.ico
  name: material
  font:
    text: DM Sans

  markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  theme:
  features:
    - content.code.copy
  palette: 
    # Dark Mode
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Dark Mode
      primary: deep purple
      accent: deep purple

    # Light mode
    - scheme: defualt
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange



